### ISSUE TITLE
Beta Test Dec 30

### ISSUE THREAD

**Issue by VictorScale82** [digforit/digforit.github.io#32]
IP address success. Intro success. Main Page function issue, where everything I try to open asks me to sign in, I sign in with TronLink and then asked to save session. If I hit save option with no password entered, I just loop back to where I was, and if I enter a password and hit save, I then freeze, and can not exit save function, i have to close tab and restart.

**Comment by VictorScale82** [comment]
IP address issue with Brave browser, Brave blocks download. Issues resolved with Chrome browser.

**Comment by digforit** [comment]
wrong github
